FROM node:22-bookworm-slim AS base

WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

FROM base AS deps

COPY package.json package-lock.json ./
RUN npm ci

FROM base AS builder

ARG APP_ENV=prod
ARG INTERNAL_API_TOKEN
ARG CLIENT_AREA_SESSION_SECRET
ARG LIVE_QUOTE_SOCKET_URL
ARG NEXT_PUBLIC_LIVE_QUOTE_SOCKET_URL
ARG NEXT_PUBLIC_FRAMER_IMAGE_BASE_URL
ARG NEWS_API_URL
ARG NEWS_API_URL_ID
ARG NEWS_API_TOKEN
ARG NEWS_PORTAL_BASE_URL
ARG NEWS_IMAGE_BASE_URL
ARG PRODUCT_API_URL
ARG EBOOK_CATEGORY_API_URL
ARG PRODUCT_PORTAL_BASE_URL
ARG SG_ADMIN_API_KEY
ARG SG_ADMIN_REQUEST_ORIGIN
ARG CLIENT_AREA_CONFIG_API_URL
ARG CLIENT_AREA_CONFIG_API_TOKEN
ARG BANNER_API_URL
ARG BANNER_DETAIL_API_URL
ARG BANNER_IMAGE_BASE_URL
ARG PENGHARGAAN_API_URL
ARG PENGHARGAAN_IMAGE_BASE_URL
ARG PENGUMUMAN_API_URL
ARG CONTACT_MESSAGE_API_URL
ARG COMPANY_PROFILE_API_URL
ARG LEGALITAS_API_URL
ARG PRIVACY_POLICY_API_URL
ARG TERMS_CONDITIONS_API_URL
ARG HISTORICAL_DATA_API_URL
ARG HISTORICAL_DATA_API_TOKEN
ARG ECONOMIC_CALENDAR_API_BASE_URL
ARG ECONOMIC_CALENDAR_API_TOKEN
ARG TRADINGVIEW_SYMBOL_API_URL
ARG MARKET_SIGNAL_API_URL
ARG MARKET_SIGNAL_IMAGE_BASE_URL
ARG MARKET_ACADEMY_API_URL
ARG FRANKFURTER_API_URL
ARG NEXT_PUBLIC_PLACEHODER_BASE_URL
ARG NEXT_PUBLIC_LOGIN_URL
ARG NEXT_PUBLIC_REGISTER_URL
ARG NEXT_PUBLIC_ENABLE_CLIENT_AREA
ARG NEXT_PUBLIC_ENABLE_TAWK_CHAT
ARG NEXT_PUBLIC_HERO_CTA_URL
ARG NEXT_PUBLIC_SPREAD_CTA_URL
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_SOLID_GOLD_PLAY_STORE_URL
ARG NEXT_PUBLIC_SOLID_GOLD_APP_STORE_URL
ARG NEXT_PUBLIC_SOLID_GOLD_IMAGE_BASE_URL
ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ARG RECAPTCHA_SECRET_KEY
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
ARG NEXT_ALLOWED_ORIGINS
ARG NEXT_SERVER_ACTIONS_ENCRYPTION_KEY
ARG DEPLOYMENT_VERSION

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN NODE_ENV=production \
    APP_ENV="$APP_ENV" \
    INTERNAL_API_TOKEN="$INTERNAL_API_TOKEN" \
    CLIENT_AREA_SESSION_SECRET="$CLIENT_AREA_SESSION_SECRET" \
    LIVE_QUOTE_SOCKET_URL="$LIVE_QUOTE_SOCKET_URL" \
    NEXT_PUBLIC_LIVE_QUOTE_SOCKET_URL="$NEXT_PUBLIC_LIVE_QUOTE_SOCKET_URL" \
    NEXT_PUBLIC_FRAMER_IMAGE_BASE_URL="$NEXT_PUBLIC_FRAMER_IMAGE_BASE_URL" \
    NEWS_API_URL="$NEWS_API_URL" \
    NEWS_API_URL_ID="$NEWS_API_URL_ID" \
    NEWS_API_TOKEN="$NEWS_API_TOKEN" \
    NEWS_PORTAL_BASE_URL="$NEWS_PORTAL_BASE_URL" \
    NEWS_IMAGE_BASE_URL="$NEWS_IMAGE_BASE_URL" \
    PRODUCT_API_URL="$PRODUCT_API_URL" \
    EBOOK_CATEGORY_API_URL="$EBOOK_CATEGORY_API_URL" \
    PRODUCT_PORTAL_BASE_URL="$PRODUCT_PORTAL_BASE_URL" \
    SG_ADMIN_API_KEY="$SG_ADMIN_API_KEY" \
    SG_ADMIN_REQUEST_ORIGIN="$SG_ADMIN_REQUEST_ORIGIN" \
    CLIENT_AREA_CONFIG_API_URL="$CLIENT_AREA_CONFIG_API_URL" \
    CLIENT_AREA_CONFIG_API_TOKEN="$CLIENT_AREA_CONFIG_API_TOKEN" \
    BANNER_API_URL="$BANNER_API_URL" \
    BANNER_DETAIL_API_URL="$BANNER_DETAIL_API_URL" \
    BANNER_IMAGE_BASE_URL="$BANNER_IMAGE_BASE_URL" \
    PENGHARGAAN_API_URL="$PENGHARGAAN_API_URL" \
    PENGHARGAAN_IMAGE_BASE_URL="$PENGHARGAAN_IMAGE_BASE_URL" \
    PENGUMUMAN_API_URL="$PENGUMUMAN_API_URL" \
    CONTACT_MESSAGE_API_URL="$CONTACT_MESSAGE_API_URL" \
    COMPANY_PROFILE_API_URL="$COMPANY_PROFILE_API_URL" \
    LEGALITAS_API_URL="$LEGALITAS_API_URL" \
    PRIVACY_POLICY_API_URL="$PRIVACY_POLICY_API_URL" \
    TERMS_CONDITIONS_API_URL="$TERMS_CONDITIONS_API_URL" \
    HISTORICAL_DATA_API_URL="$HISTORICAL_DATA_API_URL" \
    HISTORICAL_DATA_API_TOKEN="$HISTORICAL_DATA_API_TOKEN" \
    ECONOMIC_CALENDAR_API_BASE_URL="$ECONOMIC_CALENDAR_API_BASE_URL" \
    ECONOMIC_CALENDAR_API_TOKEN="$ECONOMIC_CALENDAR_API_TOKEN" \
    TRADINGVIEW_SYMBOL_API_URL="$TRADINGVIEW_SYMBOL_API_URL" \
    MARKET_SIGNAL_API_URL="$MARKET_SIGNAL_API_URL" \
    MARKET_SIGNAL_IMAGE_BASE_URL="$MARKET_SIGNAL_IMAGE_BASE_URL" \
    MARKET_ACADEMY_API_URL="$MARKET_ACADEMY_API_URL" \
    FRANKFURTER_API_URL="$FRANKFURTER_API_URL" \
    NEXT_PUBLIC_PLACEHODER_BASE_URL="$NEXT_PUBLIC_PLACEHODER_BASE_URL" \
    NEXT_PUBLIC_LOGIN_URL="$NEXT_PUBLIC_LOGIN_URL" \
    NEXT_PUBLIC_REGISTER_URL="$NEXT_PUBLIC_REGISTER_URL" \
    NEXT_PUBLIC_ENABLE_CLIENT_AREA="$NEXT_PUBLIC_ENABLE_CLIENT_AREA" \
    NEXT_PUBLIC_ENABLE_TAWK_CHAT="$NEXT_PUBLIC_ENABLE_TAWK_CHAT" \
    NEXT_PUBLIC_HERO_CTA_URL="$NEXT_PUBLIC_HERO_CTA_URL" \
    NEXT_PUBLIC_SPREAD_CTA_URL="$NEXT_PUBLIC_SPREAD_CTA_URL" \
    NEXT_PUBLIC_SITE_URL="$NEXT_PUBLIC_SITE_URL" \
    NEXT_PUBLIC_SOLID_GOLD_PLAY_STORE_URL="$NEXT_PUBLIC_SOLID_GOLD_PLAY_STORE_URL" \
    NEXT_PUBLIC_SOLID_GOLD_APP_STORE_URL="$NEXT_PUBLIC_SOLID_GOLD_APP_STORE_URL" \
    NEXT_PUBLIC_SOLID_GOLD_IMAGE_BASE_URL="$NEXT_PUBLIC_SOLID_GOLD_IMAGE_BASE_URL" \
    NEXT_PUBLIC_RECAPTCHA_SITE_KEY="$NEXT_PUBLIC_RECAPTCHA_SITE_KEY" \
    RECAPTCHA_SECRET_KEY="$RECAPTCHA_SECRET_KEY" \
    NEXT_PUBLIC_FIREBASE_API_KEY="$NEXT_PUBLIC_FIREBASE_API_KEY" \
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN" \
    NEXT_PUBLIC_FIREBASE_PROJECT_ID="$NEXT_PUBLIC_FIREBASE_PROJECT_ID" \
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET" \
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID" \
    NEXT_PUBLIC_FIREBASE_APP_ID="$NEXT_PUBLIC_FIREBASE_APP_ID" \
    NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID" \
    NEXT_ALLOWED_ORIGINS="$NEXT_ALLOWED_ORIGINS" \
    NEXT_SERVER_ACTIONS_ENCRYPTION_KEY="$NEXT_SERVER_ACTIONS_ENCRYPTION_KEY" \
    DEPLOYMENT_VERSION="$DEPLOYMENT_VERSION" \
    npm run build

FROM base AS runner

ENV NODE_ENV=production \
    HOSTNAME=0.0.0.0 \
    PORT=3000

RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 --ingroup nodejs nextjs

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

RUN mkdir -p /app/.next/cache \
    && chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]
